# PixelHub 配置文件示例
# 复制此文件为 config.toml 并填写实际配置

[server]
host = "0.0.0.0"
port = "8080"

[database]
path = "./data/pixelhub.db"

[storage]
# 存储类型：目前支持 "tencent-cos"
provider = "tencent-cos"

[storage.tencent_cos]
# 腾讯云 COS 配置
secret_id = "your-secret-id"
secret_key = "your-secret-key"
bucket_url = "https://your-bucket-1234567890.cos.ap-guangzhou.myqcloud.com"
# CDN 加速域名（可选）
cdn_url = "https://cdn.your-imagehost.com"

